apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: subscription-allow
  namespace: mindlet
  labels:
    app.kubernetes.io/name: subscription
    app.kubernetes.io/part-of: mindlet
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: subscription
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kafka
      ports:
        - protocol: TCP
          port: 9092
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: zookeeper
      ports:
        - protocol: TCP
          port: 2181
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: mindlet
      ports:
        - protocol: TCP
          port: 3000
