apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: subscription
  namespace: mindlet
  labels:
    app.kubernetes.io/name: subscription
    app.kubernetes.io/part-of: mindlet
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: subscription
