apiVersion: v1
kind: Secret
metadata:
  name: subscription-secret
  namespace: mindlet
  labels:
    app.kubernetes.io/name: subscription
    app.kubernetes.io/part-of: mindlet
type: Opaque
stringData:
  SWAGGER_USER: admin
  SWAGGER_PASSWORD: admin
  SENTRY_DSN: https://example.com/placeholder
